baseURL = "https://deep.dance"
languageCode = "en-us"
title = "deep.dance"
theme = "hermit"

[[params.videoBackground.sources]]
    source  = "/background.mp4" # Your video file
    type    = "video/mp4"
    poster  = "/background.jpg" # The image to show when the video isn't playing

[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[params]
    title = "Performing code"
    subtitle = "Premiere"
    date = "28.05.21"
    time = "20:00"
    location = "Hamburg"
    homeAnnouncement = "Infos & Code - available here soon"

[params.gpt3]
    copyright = ""
    link = "https://openai.com/"


# [[params.gpt3.list]]
#     text = "deep.dance is an dance piece created by an AI and danced by humans. It deals with the concepts of \"self-expression\" of ai.dance, \"self-identification\", \"self-death\" and \"our identity of selves.\""

[[params.intro.list]]
    text = "We tried with the AI. We danced for the AI. We did, what it choreographed for us. We asked ourselves, what does it want? We thought, maybe nothing at all. We computed our creativity. We performed."

[[params.about.list]]
    text = "In DEEP.DANCE, a team of international artists replaces themselves: A complete choreography, created by an artificial neural network by their design, is executed in detail by 3 performers. The work opens up an empathetic view into the hyper-logical world of code and statistical calculations and confronts the viewer with a construct that is accessible to few people and yet interpolates on a global scale what our future will look like. Questions are raised about the eternal hopes we project into the development of artificial intelligence and what it triggers to at last have our highly human, artistic creativity computed."

[params.team]
    title = "# TEAM"

[[params.team.list]]
    position = "Choreography"
    name = "deep.dance"

[[params.team.list]]
    position = "Project"
    name = "Jascha Viehstädt"

[[params.team.list]]
    position = "Code"
    name = "Erik Kundt, Nikolas Zöller, Lea Schorling"

[[params.team.list]]
    position = "Dance"
    name = "Raymond Liew Jin Pin, Girish Kumar"

[[params.team.list]]
    position = "Stage"
    name = "Takaya Kobayashi"

[[params.team.list]]
    position = "Outfit"
    name = "Mia Wittenhaus"

[params.funding]
    title = "# FUNDED"
    text= "**deep.dance** ist eine Produktion von [Jascha Viehstädt](http://www.jaschaviehstaedt.com). Gefördert im Rahmen des AUTONOM Programms des Fonds Darstellende Künste, von der Behörde für Kultur und Medien Hamburg, sowie der Hamburgischen Kulturstiftung."

[[params.funding.list]]
    name = "Fonds Darstellende Künste"
    href = "https://www.fonds-daku.de"
    icon = "Autonom_Logo_mitFD_custom.png"

[[params.funding.list]]
    name = "Behörde für Kultur und Medien Hamburg"
    href = "https://www.hamburg.de/bkm"
    icon = "KuM_HKS_custom.png"

[[params.funding.list]]
    name = "Hamburgische Kulturstiftung"
    href = "https://www.kulturstiftung-hh.de"
    icon = "HKS_logo_custom.png"
