
baseURL = "https://deep.dance"
# baseURL = "https://erak.github.io/deep-dance-website/"
languageCode = "en-us"
title = "deep.dance"
theme = "hermit"

[markup.goldmark.renderer]
unsafe= true

[[params.videoBackground.sources]]
    source  = "/background.mp4" # Your video file
    type    = "video/mp4"
    poster  = "/background.jpg" # The image to show when the video isn't playing

[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[params]
    title = "Deep.Dance"
    subtitle = "About Coding Choreography"
    format = "Online Opening"
    date = "17.06.2021"
    time = "20h"
    location = "Hamburg"
    homeAnnouncement = "Infos & Code - available here soon"
    nowOnline = "Now online"
    # "idle" | "prerelease" | "release" | "default"
    mode = "prerelease"

[params.gpt3]
    copyright = ""
    link = "https://openai.com/"


# [[params.gpt3.list]]
#     text = "deep.dance is an dance piece created by an AI and danced by humans. It deals with the concepts of \"self-expression\" of ai.dance, \"self-identification\", \"self-death\" and \"our identity of selves.\""

[[params.intro.list]]
    text = "Enter the hermetically soft world of code. Human, Transhuman. Machine learning. Dance. Computation. Creativity. Prediction. Soft-ware. Choreography."

[[params.about.list]]
    text = "In Deep.Dance, a team of international artists replaces itself with an artificial intelligence. A complete choreography, created by an artificial neural network that they programmed, is executed down to the last detail by three dancers. The strangely familiar movements open up an emphatic view into the hyper-logical world of code and confront the viewers with a construct that is accessible to few people and yet determines our future. The Hamburg based choreographer Jascha Viehstädt creates a silent and soft world of statistically predetermined movements that makes tangible what it means to have human creativity computed by a machine. In this way, the uncompromising simplicity of the piece offers an insight into the basic mechanisms of software and machine learning and questions the hopes and fears that are projected into the development of artificial intelligence."

[params.team]
    title = "# TEAM"

[[params.team.list]]
    position = "Choreography,"
    position_extended = "Artistic Direction"
    name = "Jascha Viehstädt"

[[params.team.list]]
    position = "AI Development,"
    position_extended = "3D-Design and Coding"
    name = "Erik Kundt, Lea Schorling, Nikolas Zöller"

[[params.team.list]]
    position = "Dance, Creation"
    name = "Girish Kumar Rachappa, Lisa Rykena, Raymond Liew Jin Pin"

[[params.team.list]]
    position = "Stage"
    name = "Takaya Kobayashi"

[[params.team.list]]
    position = "Outfit, 3D-Design"
    name = "Mia Wittenhaus"

[[params.team.list]]
    position = "Dramaturgy"
    name = "Felix Meyer-Christian"

[[params.team.list]]
    position = "Graphic Design, PR"
    name = "Julia Löffler, Lukas Besenfelder "

[[params.team.list]]
    position = "Video"
    name = "Thomas Oswald"

[[params.team.list]]
    position = "Photo"
    name = "Marcus Renner"

[[params.team.list]]
    position = "Production Assistance"
    name = "Nika Viehstädt"

[params.funding]
    title = "# FUNDED"
    text= "**deep.dance** ist eine Produktion von [Jascha Viehstädt](http://www.jaschaviehstaedt.com). Gefördert im Rahmen des AUTONOM Programms des Fonds Darstellende Künste, von der Behörde für Kultur und Medien Hamburg, sowie der Hamburgischen Kulturstiftung."

[[params.funding.list]]
    name = "Fonds Darstellende Künste"
    href = "https://www.fonds-daku.de"
    icon = "Autonom_Logo_mitFD_custom.png"

[[params.funding.list]]
    name = "Behörde für Kultur und Medien Hamburg"
    href = "https://www.hamburg.de/bkm"
    icon = "KuM_HKS_custom.png"

[[params.funding.list]]
    name = "Hamburgische Kulturstiftung"
    href = "https://www.kulturstiftung-hh.de"
    icon = "HKS_logo_custom.png"

[params.newsletter]
    headline = "Get a notification for offline events"
    description = "No spam or ads! Just an email as soon as we know how we can have a show."
    contact = "Contact: deepdance@jaschaviehstaedt.com"
    cta = "Subscribe with your email."
