baseURL = "https://deep.dance"
languageCode = "en-us"
title = "deep.dance"
theme = "hermit"

[[params.videoBackground.sources]]
    source  = "/background.mp4" # Your video file
    type    = "video/mp4"
    poster  = "/background.jpg" # The image to show when the video isn't playing

[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[params]
    homeSubtitle = "Premiere MAY 28, Hamburg"
    homeAnnouncement = "Infos & Code - available here soon"
